### ISSUE TITLE
Can't run the train script

### ISSUE THREAD

**Issue by hasan-sayeed** [Janspiry/Palette-Image-to-Image-Diffusion-Models#12]
Hi, Thanks for the amazing work!

I followed the instructions to run it but getting this error:
```
Close the Tensorboard SummaryWriter.
Traceback (most recent call last):
  File "C:\Users\Hasan Sayeed\Documents\hasan\SR3\Palette\core\logger.py", line 112, in save_images
    Image.fromarray(outputs[i]).save(os.path.join(result_path, names[i]))
  File "C:\Users\Hasan Sayeed\anaconda3\lib\site-packages\PIL\Image.py", line 2169, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'experiments\\train_inpainting_celebahq_220531_173900\\results\\val\\205\\GT_train.flist\\00037.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 103, in <module>
    main_worker(0, 1, opt)
  File "run.py", line 69, in main_worker
    model.train()
  File "C:\Users\Hasan Sayeed\Documents\hasan\SR3\Palette\core\base_model.py", line 58, in train
    val_log = self.val_step()
  File "C:\Users\Hasan Sayeed\Documents\hasan\SR3\Palette\models\model.py", line 158, in val_step
    self.writer.save_images(self.save_current_results())
  File "C:\Users\Hasan Sayeed\Documents\hasan\SR3\Palette\core\logger.py", line 114, in save_images
    raise NotImplementedError('You must specify the context of name and result in save_current_results functions of model.')
NotImplementedError: You must specify the context of name and result in save_current_results functions of model.
```
I might have missed something. Do you know what's wrong here?

**Comment by hasan-sayeed** [comment]
And here is the train log:

```
22-05-31 17:39:02.309 - INFO: Create the log file in directory experiments\train_inpainting_celebahq_220531_173900.

22-05-31 17:39:02.331 - INFO: Dataset [InpaintDataset() form data.dataset] is created.
22-05-31 17:39:02.332 - INFO: Dataset for train have 99 samples.
22-05-31 17:39:02.332 - INFO: Dataset for val have 2 samples.
22-05-31 17:39:02.672 - INFO: Network [Network() form models.network] is created.
22-05-31 17:39:02.672 - INFO: Network [Network] weights initialize using [kaiming] method.
22-05-31 17:39:02.967 - INFO: Config is a str, converts to a dict {'name': 'mae'}
22-05-31 17:39:03.195 - INFO: Metric [mae() form models.metric] is created.
22-05-31 17:39:03.195 - INFO: Config is a str, converts to a dict {'name': 'mse_loss'}
22-05-31 17:39:03.210 - INFO: Loss [mse_loss() form models.loss] is created.
22-05-31 17:39:03.211 - INFO: Optimizer [Adam() form default file] is created.
22-05-31 17:39:03.212 - INFO: Option is None when initialize Scheduler
22-05-31 17:39:03.674 - INFO: Loading pretrained model from [experiments/train_inpainting_celebahq/checkpoint/200_Network.pth] ...
22-05-31 17:39:04.662 - INFO: Loading training state for [experiments/train_inpainting_celebahq/checkpoint/200.state] ...
22-05-31 17:39:05.057 - INFO: Model [Palette() form models.model] is created.
22-05-31 17:39:05.057 - INFO: Begin model train.
22-05-31 17:39:26.918 - INFO: train/mse_loss: 0.002101995706845738	
22-05-31 17:39:26.918 - INFO: epoch: 201	
22-05-31 17:39:26.918 - INFO: iters: 933311	
22-05-31 17:39:43.346 - INFO: train/mse_loss: 0.0034099449520440294	
22-05-31 17:39:43.346 - INFO: epoch: 202	
22-05-31 17:39:43.346 - INFO: iters: 933344	
22-05-31 17:40:00.108 - INFO: train/mse_loss: 0.0033231936262878166	
22-05-31 17:40:00.108 - INFO: epoch: 203	
22-05-31 17:40:00.108 - INFO: iters: 933377	
22-05-31 17:40:17.151 - INFO: train/mse_loss: 0.0026962171268127295	
22-05-31 17:40:17.151 - INFO: epoch: 204	
22-05-31 17:40:17.151 - INFO: iters: 933410	
22-05-31 17:40:34.390 - INFO: train/mse_loss: 0.006467201443614833	
22-05-31 17:40:34.390 - INFO: epoch: 205	
22-05-31 17:40:34.390 - INFO: iters: 933443	
22-05-31 17:40:34.390 - INFO: 


------------------------------Validation Start------------------------------

```

**Comment by Janspiry** [comment]
It may be some errors in your save_current_results  function, which cause the path contains the sub dir rather than filename.![image](https://user-images.githubusercontent.com/32922494/171352724-f928c140-244d-491a-a00c-1a09bb12a383.png)

![image](https://user-images.githubusercontent.com/32922494/171351800-72e05746-5e94-493c-9036-992c63c8da44.png)

**Comment by Janspiry** [comment]
I wasn't sure what the problem was for a while. You can use the latest code, I fixed some bugs. 
It is recommended to use the -d option for quick debugging first to prevent errors when validation

**Comment by sgbaird** [comment]
@hasan-sayeed I think you never figured this out. Do you have the stack trace for the latest error?

I might try running on a Linux machine to verify.
