### ISSUE TITLE
Error During Colorization Training

### ISSUE THREAD

**Issue by YashKSahu** [Janspiry/Palette-Image-to-Image-Diffusion-Models#98]
I am getting the following error while training the colorization task. Please help me solve it.
``` bash
Traceback (most recent call last):
  File "/content/drive/MyDrive/ColabNotebooks/img2img/palette/run.py", line 92, in <module>
    main_worker(0, 1, opt)
  File "/content/drive/MyDrive/ColabNotebooks/img2img/palette/run.py", line 44, in main_worker
    model = create_model(
  File "/content/drive/MyDrive/ColabNotebooks/img2img/palette/models/__init__.py", line 10, in create_model
    model = init_obj(model_opt, logger, default_file_name='models.model', init_type='Model')
  File "/content/drive/MyDrive/ColabNotebooks/img2img/palette/core/praser.py", line 49, in init_obj
    raise NotImplementedError('{} [{:s}() form {:s}] not recognized.'.format(init_type, class_name, file_name))
NotImplementedError: Model [Palette() form models.model] not recognized.``
```

**Comment by SDD2021-car** [comment]
Maybe your checkpoint was not found.
